version: '3.7'
services:
  dbmysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p4ssw0rdr00t
      - MYSQL_PASSWORD=p4ssw0rd
      - MYSQL_USER=user_code
      - MYSQL_DATABASE=stori_db
  scriptrun:
    build: .
    depends_on:
      - dbmysql
volumes:
  db: